version: '3.1'
volumes:
  mongodata:
  pip37:
services:
  mongodb:
    image: mongo:3.2.6
    restart: always
    environment:
      MONGO_INITDB_DATABASE: employees
    container_name: mongodb
    ports:
      - "27017:27017"
  api:
    build: .
    volumes:
      - ./app:/app
    container_name: api
    environment:
      - MONGO_URI=mongodb://localhost:27017/
    command: sh -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8080 --reload"
    ports:
      - "8080:8080"
    links:
      - mongodb
  mongoseed:
    image: mongo:3.2.6
    container_name: mongo_seed
    volumes:
    - ./mongo_seed:/mongo_seed
    command:
      /mongo_seed/import.sh
    links:
      - mongodb
