version: '3.1'
volumes:
  mongo:
services:
  mongo:
    image: mongo:3.2.6
    restart: always
    env_file:
      - .env
    container_name: mongodb
  api:
    build: .
    volumes:
      - ./app:/app
    container_name: api
    environment:
      MONGO_URI: "mongodb://mongo:27017/$MONGO_DB"
    ports:
      - "8080:8080"
    command: uvicorn main:app --host 0.0.0.0 --port 8080 # python test.py   # uvicorn main:app --host 0.0.0.0 --port 8080'
    links:
      - mongo
  mongoseed:
    image: mongo:3.2.6
    container_name: mongo_seed
    volumes:
    - ./mongo_seed:/mongo_seed
    command:
      /mongo_seed/import.sh
    links:
      - mongo
